#!/bin/bash
# Generate tools/prog_data.c from built program ELF binaries
# Usage: gen_progs.sh <output.c> <build_dir> <prog1> <prog2> ...

OUT="$1"
BUILD_DIR="$2"
shift 2

echo "/* Auto-generated by gen_progs.sh - do not edit */" > "$OUT"
echo "#include <stdint.h>" >> "$OUT"
echo "#include <stddef.h>" >> "$OUT"
echo "" >> "$OUT"
echo "struct embedded_prog {" >> "$OUT"
echo "    const char *path;" >> "$OUT"
echo "    const unsigned char *data;" >> "$OUT"
echo "    size_t size;" >> "$OUT"
echo "};" >> "$OUT"
echo "" >> "$OUT"

for prog in "$@"; do
    # Determine if bin or sbin
    case "$prog" in
        ps|kill|sleep|priority|disk|rdisk|wdisk|mount|umount|svc)
            dir="/sbin"
            ;;
        *)
            dir="/bin"
            ;;
    esac

    elf="${BUILD_DIR}/bin/${prog}.elf"
    if [ ! -f "$elf" ]; then
        echo "WARNING: $elf not found, skipping" >&2
        continue
    fi

    sym=$(echo "$prog" | tr '-' '_')
    echo "static const unsigned char prog_${sym}[] = {" >> "$OUT"
    # Convert binary to comma-separated hex bytes, 16 per line
    xxd -i < "$elf" >> "$OUT"
    echo "};" >> "$OUT"
    echo "" >> "$OUT"
done

echo "const struct embedded_prog embedded_programs[] = {" >> "$OUT"

for prog in "$@"; do
    case "$prog" in
        ps|kill|sleep|priority|disk|rdisk|wdisk|mount|umount|svc)
            dir="/sbin"
            ;;
        *)
            dir="/bin"
            ;;
    esac

    elf="${BUILD_DIR}/bin/${prog}.elf"
    if [ ! -f "$elf" ]; then
        continue
    fi

    sym=$(echo "$prog" | tr '-' '_')
    sz=$(stat -c%s "$elf")
    echo "    { \"${dir}/${prog}\", prog_${sym}, ${sz} }," >> "$OUT"
done

echo "    { NULL, NULL, 0 }" >> "$OUT"
echo "};" >> "$OUT"
echo "" >> "$OUT"
echo "const int embedded_program_count = (sizeof(embedded_programs)/sizeof(embedded_programs[0])) - 1;" >> "$OUT"
